services:

  backend:
    build: .
    restart: always
    container_name: "link_backend"
    command: bash -c "python ./link/manage.py makemigrations && python ./link/manage.py migrate && uwsgi --ini /home/workspace/link/uwsgi.ini"
    ports:
      - "8000:8000"
      - "4010:4010"
    links: 
      - pgsql
    depends_on:
      - pgsql
      - redis


  emqx:
    image: "emqx/emqx:latest"
    restart: always
    container_name: "link_emqx"
    links: 
      - pgsql
      - backend
    depends_on:
      - pgsql
    ports:
      - "18083:18083"
      - "8083:8083"
      - "1883:1883"
      - "4369:4369"
    environment:
      - "EMQX_LOADED_PLUGINS=emqx_dashboard,emqx_auth_pgsql,emqx_exhook"
      - "EMQX_ALLOW_ANONYMOUS=false"
      - "EMQX_ACL_NOMATCH=deny"
      - "EMQX_ACL_DENY_ACTION=disconnect"
      - "EMQX_AUTH__PGSQL__SERVER=link_pgsql:5432"
      - "EMQX_AUTH__PGSQL__USERNAME=admin"
      - "EMQX_AUTH__PGSQL__PASSWORD=admin"
      - "EMQX_AUTH__PGSQL__PASSWORD_HASH=plain"
      - "EMQX_AUTH__PGSQL__DATABASE=link"
      - "EMQX_AUTH__PGSQL__AUTH_QUERY=select token from device where client_id = '%c' and client_name = '%u' limit 1"
      - "EMQX_AUTH__PGSQL__SUPER_QUERY=select is_super from device where client_id = '%c' and client_name = '%u' limit 1"
      - "EMQX_AUTH__PGSQL__ACL_QUERY=select allow, ipaddr, username, clientid, access, topic from emqx_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'"
      - "EMQX_EXHOOK__SERVER__DEFAULT__URL=http://link_backend:4010"

  redis:
    image: "redis:latest"
    container_name: "link_redis"
    restart: always
    ports:
      - "6379:6379"

  pgsql:
    image: "postgres:12"
    container_name: "link_pgsql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "link"
    volumes:
      - "./data/pg:/var/lib/postgresql/data"
