services:

  emqx:
    network_mode: "host"
    image: "emqx/emqx:4.4.16"
    restart: always
    container_name: "link_emqx"
    environment:
      EMQX_LOADED_PLUGINS: 'emqx_dashboard,emqx_auth_http,emqx_web_hook'
      # 禁止匿名登录
      EMQX_ALLOW_ANONYMOUS: 'false'
      EMQX_ACL_NOMATCH: 'deny'
      EMQX_ACL_DENY_ACTION: 'disconnect'
      # 客户端最大允许的Qos
      EMQX_MQTT__MAX_QOS_ALLOWED: 0
      EMQX_MQTT__MAX_QOS_ALLOWED: 0

      EMQX_ZONE__EXTERNAL__RATE_LIMIT__CONN_MESSAGES_IN: '1,10s'
      # auth鉴权
      EMQX_AUTH__HTTP__AUTH_REQ__URL: 'http://localhost:8000/api/emqx/auth/'
      EMQX_AUTH__HTTP__AUTH_REQ__METHOD: 'post'
      EMQX_AUTH__HTTP__AUTH_REQ__CONTENT_TYPE: 'json'
      EMQX_AUTH__HTTP__AUTH_REQ__PARAMS: 'client_id=%c,username=%u,password=%P,ip_address=%a,protocol=%r'
      # acl鉴权
      EMQX_AUTH__HTTP__ACL_REQ__URL: 'http://localhost:8000/api/emqx/acl/'
      EMQX_AUTH__HTTP__ACL_REQ__METHOD: 'post'
      EMQX_AUTH__HTTP__ACL_REQ__CONTENT_TYPE: 'json'
      EMQX_AUTH__HTTP__ACL_REQ__PARAMS: 'access=%A,username=%u,client_id=%c,ip_address=%a,topic=%t,mount_point=%m,protocol=%r'
      # web_hooks
      EMQX_WEB__HOOK__URL: 'http://localhost:8000/api/emqx/hooks/'
      EMQX_WEB__HOOK__RULE__CLIENT__CONNECTED__1: '{"action":"on_client_connected"}'
      EMQX_WEB__HOOK__RULE__CLIENT__DISCONNECTED__1: '{"action":"on_client_disconnected"}'
      EMQX_WEB__HOOK__RULE__MESSAGE__PUBLISH__1: '{"action":"on_message_publish"}'
      EMQX_WEB__HOOK__RULE__SESSION__SUBSCRIBED__1: '{"action":"on_session_subscribed"}'
      EMQX_WEB__HOOK__RULE__SESSION__UNSUBSCRIBED__1: '{"action":"on_session_unsubscribed"}'
      # emqx_management http api basic auth 配置
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__id: 'admin'
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: 'admin'

  redis:
    network_mode: "host"
    image: "redis:latest"
    container_name: "link_redis"
    restart: always

  pgsql:
    network_mode: "host"
    image: "timescale/timescaledb:latest-pg14"
    container_name: "link_pgsql"
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "link"
    volumes:
      - "/data/link_pgsql_dev:/var/lib/postgresql/data"
