[tool.black]
exclude = '''
miniprogram/.*
'''
line-length = 100
target-version = ["py38"]

[tool.isort]
profile = "black"
skip = ["migrations"] 
py_version = 38
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
use_parentheses = true
length_sort = true
src_paths = ["link/*", "services/*"]
